### ISSUE TITLE
Пример приложения ToDo

### ISSUE THREAD

**Issue by gennady-lebedev** [rudiments-dev/hardcore#25]
Нужен пример реализации для проработки (в первую очередь - инфраструктуры) UI.
Приложение ToDo list, пока чистый REST:
- CRUD заметки (Item)
  - Create - POST (без ID)
  - Read - GET
  - Update - PUT
  - Delete - DELETE
- выполнение отдельно
  - /done - выполнить, если не выполнена
  - /undone - не выполнена, если сейчас done

Отдельно будет:
- WS-стрим для событий из приложения (нужно прорабатывать бэк, аспекты хранения и публикации во всех, кто запросил)
- alarm - после реализации WS, будет иметь смысл, т.к. alarm это событие, которое отдалено во времени от запроса (де-факто это как внешнее событие в случайный момент времени)

**Comment by gennady-lebedev** [comment]
Переписал страницу https://github.com/rudiments-dev/hardcore/wiki/ToDo-example-app
Описал контракт в ветке https://github.com/rudiments-dev/hardcore/blob/%2325/todo-example-app/todo-example-app/todo.yaml

Драфт (пока не рабочий дальше CRUD) так же в ветке.

**Comment by ignatev** [comment]
Беру юай на себя.

**Comment by ignatev** [comment]
Создание новых туду через POST сейчас работает?

**Comment by gennady-lebedev** [comment]
Ребейзнул от #34, сделал так чтобы FindAll всегда выполнялся без кэширования.
Обращаю внимание, что сейчас генерация ID не работает (поправлю когда буду делать #42)

**Comment by gennady-lebedev** [comment]
Выпилил использование результатов из control flow (кэширование), сейчас должно работать без странных эффектов.
