### ISSUE TITLE
Describe contract for demo application

### ISSUE THREAD

**Issue by ignatev** [rudiments-dev/hardcore#3]

**Comment by gennady-lebedev** [comment]
https://github.com/rudiments-dev/hardcore/wiki/ToDo-sample-app драфт, завтра дополню

**Comment by gennady-lebedev** [comment]
Плохое было описание, завел формальный OAS 3.0 контракт в https://github.com/rudiments-dev/hardcore/blob/%2325/todo-example-app/todo-example-app/todo.yaml

В https://github.com/rudiments-dev/hardcore/wiki/ToDo-example-app описал примерный порядок как будет развиваться приложение

**Comment by gennady-lebedev** [comment]
Ради рефакторинга перенес в ветку https://github.com/rudiments-dev/hardcore/blob/%2325/todo-app/todo-example-app/todo.yaml
