### ISSUE TITLE
Сборка падает с ошибкой scaladoc 

### ISSUE THREAD

**Issue by gennady-lebedev** [rudiments-dev/hardcore#36]
https://travis-ci.org/github/rudiments-dev/hardcore/builds/688158137

При выполнении `./gradlew build` падает `:db-registry:scaladoc` и `:implementation:scaladoc` с сообщением что папок `<module>/build/classes/java/main` и `<module>/build/resources/main` не существует.

Раньше такой херни не было, при этом gradle-скрипты не обновлялись существенно в этом году, не то что последние месяцы.

Из IDE сборка работает нормально, тесты проходят.

**Comment by gennady-lebedev** [comment]
Пока единственная мысль вокруг ошибки - где-то допустил некорректное имя класса, которое вызвало коллизию сборки. Изучу дельту и попробую поренеймить, но все равно странно.

**Comment by ignatev** [comment]
Сейчас не воспроизводится, закрыто.
